pragma Singleton

import Quickshell

// Reads and writes Hyprland monitor rules, both as Lua (hl.monitor({ ... })) and legacy hyprlang (monitor = ...).
// A rule is { output, fields: [{ key, raw, value }] }, where raw is the source text of the value (kept so fields
// we don't understand survive a round trip) and value is the parsed literal, or undefined for expressions.
Singleton {
    id: root

    function parse(text: string, lua: bool): var {
        return lua ? parseLua(text) : parseHyprlang(text);
    }

    function parseLua(text: string): var {
        const src = stripLuaComments(text);
        const rules = [];
        let i = 0;

        while (i < src.length) {
            const c = src[i];
            if (c === "\"" || c === "'") {
                i = skipLuaString(src, i);
                continue;
            }
            if (c === "[") {
                const end = longBracketEnd(src, i);
                if (end >= 0) {
                    i = end;
                    continue;
                }
            }
            if (c === "h" && !/[\w.:]/.test(src[i - 1] ?? "")) {
                const call = /^hl\s*\.\s*monitor\s*\(\s*\{/.exec(src.slice(i, i + 64));
                if (call) {
                    const table = readLuaTable(src, i + call[0].length - 1);
                    const rule = ruleFromPairs(table.pairs, true);
                    if (rule)
                        rules.push(rule);
                    i = table.end;
                    continue;
                }
            }
            i++;
        }

        return rules;
    }

    function parseHyprlang(text: string): var {
        const rules = [];

        for (const rawLine of text.split("\n")) {
            const line = stripHyprComment(rawLine);
            const match = /^\s*monitor\s*=\s*(.*)$/.exec(line);
            if (!match)
                continue;

            const parts = match[1].split(",").map(p => p.trim());
            const pairs = [
                {
                    key: "output",
                    raw: parts[0]
                }
            ];

            if (/^disabled?$/.test(parts[1] ?? "")) {
                pairs.push({
                    key: "disabled",
                    raw: "true"
                });
            } else {
                const positional = ["mode", "position", "scale"];
                for (let p = 0; p < positional.length; p++) {
                    if (parts[p + 1])
                        pairs.push({
                            key: positional[p],
                            raw: parts[p + 1]
                        });
                }
                for (let p = 4; p + 1 < parts.length; p += 2)
                    pairs.push({
                        key: parts[p],
                        raw: parts[p + 1]
                    });
            }

            const rule = ruleFromPairs(pairs, false);
            if (rule)
                rules.push(rule);
        }

        return rules;
    }

    function serialize(rules: var, lua: bool): string {
        const header = lua ? "--" : "#";
        const lines = [`${header} Generated by the Caelestia shell (Nexus > Display)`, `${header} This file is rewritten whenever display settings are saved from Nexus`, ""];
        for (const rule of rules)
            lines.push(lua ? luaCall(rule) : `monitor = ${hyprLine(rule, ", ")}`);
        return lines.join("\n") + "\n";
    }

    function command(rule: var, lua: bool): string {
        if (lua)
            return `eval ${luaCall(rule).replace(/\s*\n\s*/g, " ").replace(/;/g, "\\;")}`;
        return `keyword monitor ${hyprLine(rule, ",")}`;
    }

    // The last matching rule wins, same as Hyprland. The fallback rule (empty output) is not matched here.
    function find(rules: var, mon: var): var {
        let found = null;
        for (const rule of rules)
            if (matches(rule, mon))
                found = rule;
        return found;
    }

    function matches(rule: var, mon: var): bool {
        const output = rule.output.trim();
        if (!output)
            return false;
        if (output.startsWith("desc:")) {
            const desc = output.slice(5).trim();
            if (!desc)
                return false;
            const full = [mon.make, mon.model, mon.serial].filter(s => s).join(" ");
            return (mon.description ?? "").startsWith(desc) || full.startsWith(desc);
        }
        return output === mon.name;
    }

    function field(rule: var, key: string): var {
        return rule?.fields.find(f => f.key === key) ?? null;
    }

    function value(rule: var, key: string): var {
        return field(rule, key)?.value;
    }

    // Returns a copy of the rule with the given fields replaced, or appended in the given order if missing
    function withFields(rule: var, values: var, lua: bool): var {
        const fields = rule.fields.map(f => Object.assign({}, f));
        for (const key of Object.keys(values)) {
            const f = {
                key: key,
                raw: rawValue(values[key], lua),
                value: values[key]
            };
            const idx = fields.findIndex(e => e.key === key);
            if (idx >= 0)
                fields[idx] = f;
            else
                fields.push(f);
        }
        return {
            output: rule.output,
            fields: fields
        };
    }

    function withoutFields(rule: var, keys: var): var {
        return {
            output: rule.output,
            fields: rule.fields.filter(f => !keys.includes(f.key))
        };
    }

    function hasInclude(text: string, lua: bool): bool {
        if (lua) {
            const src = stripLuaComments(text);
            return /(^|[^\w.:])require\s*\(?\s*["']hypr-monitors["']/.test(src) || /(^|[^\w.:])(dofile|loadfile)\s*\(?[^\n]*hypr-monitors\.lua/.test(src);
        }
        return text.split("\n").some(l => /^\s*source\s*=.*hypr-monitors\.conf\s*$/.test(stripHyprComment(l)));
    }

    function includeSnippet(lua: bool, path: string): string {
        if (lua)
            return "\n-- Display settings saved from Nexus\nrequire(\"hypr-monitors\")\n";
        return `\n# Display settings saved from Nexus\nsource = ${path}\n`;
    }

    function rawValue(val: var, lua: bool): string {
        if (typeof val === "number")
            return String(Math.round(val * 1e6) / 1e6);
        if (typeof val === "boolean")
            return String(val);
        if (!lua)
            return String(val);
        return `"${String(val).replace(/\\/g, "\\\\").replace(/"/g, "\\\"")}"`;
    }

    function literal(raw: string, lua: bool): var {
        if (/^-?(\d+\.?\d*|\.\d+)([eE][-+]?\d+)?$/.test(raw))
            return Number(raw);
        if (raw === "true" || raw === "false")
            return raw === "true";
        if (!lua)
            return raw;

        const str = /^"((?:[^"\\\n]|\\.)*)"$/.exec(raw) ?? /^'((?:[^'\\\n]|\\.)*)'$/.exec(raw);
        if (str)
            return str[1].replace(/\\(.)/g, (_, ch) => ch === "n" ? "\n" : ch === "t" ? "\t" : ch);
        return undefined;
    }

    function ruleFromPairs(pairs: var, lua: bool): var {
        const fields = [];
        let output;

        for (const pair of pairs) {
            if (pair.key === "output") {
                output = literal(pair.raw, lua);
                continue;
            }
            // Later duplicates win, as with Lua table constructors
            const idx = fields.findIndex(f => f.key === pair.key);
            if (idx >= 0)
                fields.splice(idx, 1);
            fields.push({
                key: pair.key,
                raw: pair.raw,
                value: literal(pair.raw, lua)
            });
        }

        if (typeof output !== "string")
            return null;
        return {
            output: output,
            fields: fields
        };
    }

    function luaCall(rule: var): string {
        const parts = [`output = ${rawValue(rule.output, true)}`];
        for (const f of rule.fields)
            parts.push(`${f.key} = ${f.raw}`);
        return `hl.monitor({ ${parts.join(", ")} })`;
    }

    function hyprLine(rule: var, sep: string): string {
        if (value(rule, "disabled") === true)
            return [rule.output, "disable"].join(sep);

        const positional = ["mode", "position", "scale"];
        const defaults = ["preferred", "auto", "auto"];
        const parts = [rule.output, ...positional.map((k, i) => field(rule, k)?.raw ?? defaults[i])];
        for (const f of rule.fields)
            if (!positional.includes(f.key) && f.key !== "disabled")
                parts.push(f.key, f.raw);
        return parts.join(sep);
    }

    function readLuaTable(src: string, open: int): var {
        const pairs = [];
        let depth = 0;
        let start = open + 1;
        let i = open;

        const pushPair = segment => {
            const match = /^([A-Za-z_]\w*)\s*=\s*([^]+)$/.exec(segment.trim());
            if (match)
                pairs.push({
                    key: match[1],
                    raw: match[2].trim()
                });
        };

        while (i < src.length) {
            const c = src[i];
            if (c === "\"" || c === "'") {
                i = skipLuaString(src, i);
                continue;
            }
            if (c === "[") {
                const end = longBracketEnd(src, i);
                if (end >= 0) {
                    i = end;
                    continue;
                }
            }

            if (c === "{" || c === "(" || c === "[") {
                depth++;
            } else if (c === "}" || c === ")" || c === "]") {
                depth--;
                if (depth === 0) {
                    pushPair(src.slice(start, i));
                    return {
                        pairs: pairs,
                        end: i + 1
                    };
                }
            } else if ((c === "," || c === ";") && depth === 1) {
                pushPair(src.slice(start, i));
                start = i + 1;
            }
            i++;
        }

        return {
            pairs: pairs,
            end: src.length
        };
    }

    // Replaces comments with spaces, leaving strings alone
    function stripLuaComments(text: string): string {
        let out = "";
        let i = 0;

        while (i < text.length) {
            const c = text[i];
            if (c === "\"" || c === "'") {
                const end = skipLuaString(text, i);
                out += text.slice(i, end);
                i = end;
            } else if (c === "-" && text[i + 1] === "-") {
                let end = text[i + 2] === "[" ? longBracketEnd(text, i + 2) : -1;
                if (end < 0) {
                    end = text.indexOf("\n", i);
                    if (end < 0)
                        end = text.length;
                }
                out += " ".repeat(end - i);
                i = end;
            } else if (c === "[" && longBracketEnd(text, i) >= 0) {
                const end = longBracketEnd(text, i);
                out += text.slice(i, end);
                i = end;
            } else {
                out += c;
                i++;
            }
        }

        return out;
    }

    function skipLuaString(text: string, start: int): int {
        const quote = text[start];
        let i = start + 1;
        while (i < text.length) {
            const c = text[i];
            if (c === "\\")
                i += 2;
            else if (c === quote)
                return i + 1;
            else if (c === "\n")
                return i;
            else
                i++;
        }
        return text.length;
    }

    // Index after a long bracket ([[ ]], [==[ ]==]) starting at start, or -1 if there isn't one
    function longBracketEnd(text: string, start: int): int {
        const open = /^\[(=*)\[/.exec(text.slice(start, start + 16));
        if (!open)
            return -1;
        const close = text.indexOf(`]${open[1]}]`, start + open[0].length);
        return close < 0 ? text.length : close + open[1].length + 2;
    }

    function stripHyprComment(line: string): string {
        return line.replace(/##/g, "\u0000").replace(/#.*$/, "").replace(/\u0000/g, "#");
    }
}
